# Generated by Django 4.1.4 on 2023-01-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_order_products_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
