# Generated by Django 4.1.4 on 2023-01-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_payment_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='security_code',
            field=models.IntegerField(),
        ),
    ]
