# Generated by Django 4.1.4 on 2023-01-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
