# Generated by Django 4.1.4 on 2023-01-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
